name: smart_track
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  # flutter_local_notifications: ^19.1.0 
  connectivity_plus: ^4.0.2
  fluttertoast: ^8.2.2
  shared_preferences: ^2.5.2
  fl_chart: ^0.70.0
  intl: ^0.20.1
  http: ^1.2.1
  timezone: ^0.10.1
  shimmer: ^2.0.0
  audioplayers: ^6.4.0
  flutter_blue_plus: ^1.35.3
  flutter_heatmap_calendar: ^1.0.5
  pull_to_refresh: ^2.0.0
  table_calendar: ^3.2.0
  slide_to_act: ^2.0.2
  beacon_broadcast: ^0.3.1
  permission_handler: ^12.0.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Thin.ttf
          weight: 100
        - asset: assets/font/Roboto-ThinItalic.ttf
          weight: 100

  